package Mainpackage;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

public class LoadingScreen extends javax.swing.JFrame {

    public void startApp() {        
        try {
            //This will make the title appear under the logo
            TitleName.setText("  Unicalc Pro");
            
            Thread.sleep(1500); //default 1000
            //this is used for stopping the logo's movement
            LoadingPanel.removeAll();
            
            //this will make 1 second delay
            Thread.sleep(1000);
            
            //This will close the loading screen
            dispose();
            
            //This will bring the application frame (TheFrame) into the screen in Nimbus look 
            String[] args = null;
            new TheFrame().main(args);
            
        } catch (InterruptedException ex) {
            Logger.getLogger(TheFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public LoadingScreen() {
        initComponents();
        
        //Setting the icon image for the application
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/AppIcons/logo.png")));
        //setting the loading screen in the middle of the screen
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LoadingPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TitleName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 550));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        LoadingPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoadingPanel.setLayout(new java.awt.GridBagLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppIcons/loadingLogo.gif"))); // NOI18N
        LoadingPanel.add(jLabel5, new java.awt.GridBagConstraints());

        TitleName.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        TitleName.setForeground(new java.awt.Color(0, 146, 183));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        LoadingPanel.add(TitleName, gridBagConstraints);

        getContentPane().add(LoadingPanel, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoadingPanel;
    private javax.swing.JLabel TitleName;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
