package Panels.Converter;

import Mainpackage.*;

public class Area extends javax.swing.JPanel {

    double m;

    public Area() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ApplicationWindow = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        TypeDisplay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TypeDisplay1 = new javax.swing.JTextField();
        ConvertButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        validity1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 153));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        ApplicationWindow.setMinimumSize(new java.awt.Dimension(700, 500));
        ApplicationWindow.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Area Conversion");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To:");

        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Square Meter", "Square Kilometer", "Square Centimeter", "Square Millimeter", "Acre", "Square Mile", "Square Yard", "Square Foot", "Square Inch" }));

        jComboBox2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Square Meter", "Square Kilometer", "Square Centimeter", "Square Millimeter", "Acre", "Square Mile", "Square Yard", "Square Foot", "Square Inch" }));

        TypeDisplay.setBackground(new java.awt.Color(204, 204, 204));
        TypeDisplay.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        TypeDisplay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TypeDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TypeDisplayKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("From:");

        TypeDisplay1.setEditable(false);
        TypeDisplay1.setBackground(new java.awt.Color(204, 204, 204));
        TypeDisplay1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        TypeDisplay1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ConvertButton.setBackground(new java.awt.Color(44, 60, 76));
        ConvertButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ConvertButton.setForeground(new java.awt.Color(255, 255, 255));
        ConvertButton.setText("Convert");
        ConvertButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        validity1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        validity1.setForeground(new java.awt.Color(215, 0, 0));

        javax.swing.GroupLayout ApplicationWindowLayout = new javax.swing.GroupLayout(ApplicationWindow);
        ApplicationWindow.setLayout(ApplicationWindowLayout);
        ApplicationWindowLayout.setHorizontalGroup(
            ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ApplicationWindowLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ApplicationWindowLayout.createSequentialGroup()
                        .addComponent(ConvertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ApplicationWindowLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(208, 208, 208))))
            .addGroup(ApplicationWindowLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ApplicationWindowLayout.createSequentialGroup()
                        .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ApplicationWindowLayout.createSequentialGroup()
                        .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TypeDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                                .addComponent(TypeDisplay1))
                            .addComponent(validity1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        ApplicationWindowLayout.setVerticalGroup(
            ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplicationWindowLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TypeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validity1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TypeDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(ConvertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(ApplicationWindow, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertButtonActionPerformed
        try{
            //:::::::::::::::::Getting Selected item from input combobox:::::::::::::::::://
            String box1 = (String)jComboBox1.getSelectedItem();

            //Comparing the selected item
            //Changing the input value to base value(Square Meter)
            switch (box1) {
                case "Square Meter":
                    double Meter = Double.parseDouble(TypeDisplay.getText());
                    m = Meter;
                    break;
                    
                case "Square Kilometer":
                    double KilometerToMeter = Double.parseDouble(TypeDisplay.getText());
                    m = KilometerToMeter*1000000.0;
                    break;
                    
                case "Square Centimeter":
                    double CentimeterToMeter = Double.parseDouble(TypeDisplay.getText());
                    m = CentimeterToMeter*0.0001;
                    break;
                    
                case "Square Millimeter":
                    double MillimeterToMeter = Double.parseDouble(TypeDisplay.getText());
                    m = MillimeterToMeter*0.000001;
                    break;
                    
                case "Acre":
                    double Acre = Double.parseDouble(TypeDisplay.getText());
                    m = Acre*4046.8564224;
                    break;
                    
                case "Square Mile":
                    double MileToMeter = Double.parseDouble(TypeDisplay.getText());
                    m = MileToMeter*2589988.1103;
                    break;
                    
                case "Square Yard":
                    double Yard = Double.parseDouble(TypeDisplay.getText());
                    m = Yard*0.83612736;
                    break;
                    
                case "Square Foot":
                    double FootToMeter = Double.parseDouble(TypeDisplay.getText());
                    m = FootToMeter*0.09290304;
                    break;
                    
                case "Square Inch":
                    double InchToMeter = Double.parseDouble(TypeDisplay.getText());
                    m = InchToMeter*0.00064516;
                    break;
                    
                default:
                    throw new InputException("Select a area unit.");
            }


            //::::::::::::::::::Getting Selected item from output combobox::::::::::::::://
            String box2 = (String)jComboBox2.getSelectedItem();

            //Comparing the selected item
            //Changing(from Square Meter) the output value to desired value
            switch (box2) {
                case "Square Meter":
                    double MeterToMeter = m;  
                    TypeDisplay1.setText(String.valueOf(MeterToMeter));
                    break;
                    
                case "Square Kilometer":
                    double MeterTOKilometer = (m*0.000001);
                    TypeDisplay1.setText(String.valueOf(MeterTOKilometer));
                    break;
                    
                case "Square Centimeter":
                    double CentimeterToMeter = m*10000.0;
                    TypeDisplay1.setText(String.valueOf(CentimeterToMeter));
                    break;
                    
                case "Square Millimeter":
                    double MillimeterToMeter = m*1000000.0;
                    TypeDisplay1.setText(String.valueOf(MillimeterToMeter));
                    break;
                    
                case "Acre":
                    double Acre = m*0.0002471054;
                    TypeDisplay1.setText(String.valueOf(Acre));
                    break;
                    
                case "Square Mile":
                    double MileToMeter = Math.pow(10, -7)*3.861021585*m;
                    TypeDisplay1.setText(String.valueOf(MileToMeter));
                    break;
                    
                case "Square Yard":
                    double Yard = m*1.1959900463;
                    TypeDisplay1.setText(String.valueOf(Yard));
                    break;
                    
                case "Square Foot":
                    double FootToMeter = m*10.763910417;
                    TypeDisplay1.setText(String.valueOf(FootToMeter));
                    break;
                    
                case "Square Inch":
                    double InchToMeter = m*1550.0031;
                    TypeDisplay1.setText(String.valueOf(InchToMeter));
                    break;
                    
                default:
                    throw new InputException("Select a area unit.");
            }
        }catch(InputException e){
            
        }catch(Exception e){
            ErrorWindow ob = new ErrorWindow();        
            ob.setErrorText("Invalid Input");
            ob.setVisible(true);
        }   
    }//GEN-LAST:event_ConvertButtonActionPerformed

    private void TypeDisplayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TypeDisplayKeyPressed
             
        try{
            double i = Double.parseDouble(TypeDisplay.getText());
            validity1.setText("");
        }catch(NumberFormatException e1){
            validity1.setText("Invalid Input");
        }
        
    }//GEN-LAST:event_TypeDisplayKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ApplicationWindow;
    private javax.swing.JButton ConvertButton;
    private javax.swing.JTextField TypeDisplay;
    private javax.swing.JTextField TypeDisplay1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel validity1;
    // End of variables declaration//GEN-END:variables
}
