package Panels.Calculator;

import Mainpackage.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public class AgeCalculator extends javax.swing.JPanel {

    public AgeCalculator() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ApplicationWindow = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DateOfBirth = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        CurrentDate = new com.toedter.calendar.JDateChooser();
        CalculateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AgeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NextBirField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 153));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        ApplicationWindow.setMinimumSize(new java.awt.Dimension(700, 500));
        ApplicationWindow.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Age Calculator");
        jLabel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date of Birth:");

        DateOfBirth.setDateFormatString("dd-MM-yyyy");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Today's Date:");

        CurrentDate.setDateFormatString("dd-MM-yyyy");

        CalculateButton.setBackground(new java.awt.Color(44, 60, 76));
        CalculateButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CalculateButton.setForeground(new java.awt.Color(255, 255, 255));
        CalculateButton.setText("Calculate");
        CalculateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age:");

        AgeField.setEditable(false);
        AgeField.setBackground(new java.awt.Color(204, 204, 204));
        AgeField.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        AgeField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Next Birthday:");

        NextBirField.setEditable(false);
        NextBirField.setBackground(new java.awt.Color(204, 204, 204));
        NextBirField.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        NextBirField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ApplicationWindowLayout = new javax.swing.GroupLayout(ApplicationWindow);
        ApplicationWindow.setLayout(ApplicationWindowLayout);
        ApplicationWindowLayout.setHorizontalGroup(
            ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplicationWindowLayout.createSequentialGroup()
                .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ApplicationWindowLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ApplicationWindowLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(NextBirField, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ApplicationWindowLayout.createSequentialGroup()
                                .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(DateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(133, 133, 133)
                                .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(CurrentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ApplicationWindowLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ApplicationWindowLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(223, 223, 223))
            .addGroup(ApplicationWindowLayout.createSequentialGroup()
                .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ApplicationWindowLayout.setVerticalGroup(
            ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplicationWindowLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ApplicationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NextBirField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(ApplicationWindow, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        try {
            //Clearing the Age and Next Birthday's TextField Everytime
            AgeField.setText("");
            NextBirField.setText("");
            
            //Setting up date format
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            //Getting Date Strings from Date of birth and current date field
            String fromDate = sdf.format(DateOfBirth.getDate());
            String toDate = sdf.format(CurrentDate.getDate());
            
            //Converting Date strings to the following date format
            Date dateOb1 = sdf.parse(fromDate);
            Date dateOb2 = sdf.parse(toDate);

            //Getting date difference in milliseconds
            long diff = dateOb2.getTime() - dateOb1.getTime(); 
            //converting Milliseconds to Days
            int diffDays = (int) (diff / (24 * 60 * 60 * 1000));  
            
            //Handling invalid date exceptions
            if(diffDays == 0)
                throw new InputException("Congratulations! You have just born today.");
            else if (diffDays < 0)
                throw new InputException("Are you a Time-Traveller?");
            
            //::::::::::::::::::Calculationg Year, Month, Day:::::::::::::::::://
            int resYear, resMonth, resDay;
            resYear = diffDays / 365;           //Total Year..
            resMonth = (diffDays % 365) /31;    //Remaining Month after calculating year
            resDay = (diffDays % 365) % 31;     //Remaining Day after calculating month
            
            //Showing Year if it is greater than 0
            if(resYear != 0){
                if(resYear ==1)    
                    AgeField.setText(resYear+" Year   "+AgeField.getText());
                else 
                    AgeField.setText(resYear+" Years   "+AgeField.getText());
            }
            //Showing Month if it is greater than 0
            if(resMonth != 0){
                if(resMonth ==1)    
                    AgeField.setText(AgeField.getText()+resMonth+" Month   ");
                else 
                    AgeField.setText(AgeField.getText()+resMonth+" Months   ");
            }
            //Showing Day if it is greater than 0
            if(resDay != 0){
                if(resDay ==1)    
                    AgeField.setText(AgeField.getText()+resDay+" Day");
                else 
                    AgeField.setText(AgeField.getText()+resDay+" Days");
            }
            
            
            //::::::::::::::::::Calculating next birthday:::::::::::::::::://
            int nexMonth, nexDay;
            
           /*(((diffDays) % 365 ) /31) this returns the month which is less than 12.
              When month hits 12, it counts as a Year.*/
            nexMonth = 11-(((diffDays) % 365 ) /31);
            /*(((diffDays) % 365 ) %31) this returns the day which is less than 30.
              When day hits 30, it counts as a month.*/
            nexDay = 30-(diffDays % 365) % 31;
            
            //Showing "In" string before the next birthday
            NextBirField.setText("In ");
            
            //Showing Month if it is greater than 0
            if(nexMonth != 0){
                if(nexMonth ==1)    
                    NextBirField.setText(NextBirField.getText()+nexMonth+" Month   ");
                else 
                    NextBirField.setText(NextBirField.getText()+nexMonth+" Months   ");
            }
            //Showing Day if it is greater than 0
            if(nexDay != 0){
                if(nexDay ==1)    
                    NextBirField.setText(NextBirField.getText()+nexDay+" Day");
                else 
                    NextBirField.setText(NextBirField.getText()+nexDay+" Days");
            }
            
            
 
        }catch(InputException e){
        }catch(Exception e){
            ErrorWindow ob = new ErrorWindow();        
            ob.setErrorText("Invalid Date Format. Expected Format: dd-MM-yyyy");
            ob.setVisible(true);
        }  
    }//GEN-LAST:event_CalculateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeField;
    private javax.swing.JPanel ApplicationWindow;
    private javax.swing.JButton CalculateButton;
    private com.toedter.calendar.JDateChooser CurrentDate;
    private com.toedter.calendar.JDateChooser DateOfBirth;
    private javax.swing.JTextField NextBirField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
