package Panels.Calculator;

import Mainpackage.*;

public class ScientificCalculator extends javax.swing.JPanel {

    public ScientificCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ApplicationWindow = new javax.swing.JPanel();
        border1 = new javax.swing.JPanel();
        border2 = new javax.swing.JPanel();
        DisplayPanel = new javax.swing.JPanel();
        TypeDisplay = new javax.swing.JTextField();
        AnswerDisplay1 = new javax.swing.JTextField();
        Back = new javax.swing.JTextField();
        NumberPanel = new javax.swing.JPanel();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        acButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        signButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        expButton = new javax.swing.JButton();
        dotButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        ShiftKeyPanel = new javax.swing.JPanel();
        DefPanel1 = new javax.swing.JPanel();
        sqrButton = new javax.swing.JButton();
        sqrtButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        xinvButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PressedShift1 = new javax.swing.JPanel();
        xpwrButton = new javax.swing.JButton();
        cubicRtButton = new javax.swing.JButton();
        xFactButton = new javax.swing.JButton();
        AntilogButton = new javax.swing.JButton();
        TrigonomerticPanel = new javax.swing.JPanel();
        DefPanel2 = new javax.swing.JPanel();
        sinButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        tanButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PressedShift2 = new javax.swing.JPanel();
        invSinButton = new javax.swing.JButton();
        invCosButton = new javax.swing.JButton();
        invTanButton = new javax.swing.JButton();
        PressedHyp = new javax.swing.JPanel();
        tanhButton = new javax.swing.JButton();
        coshButton = new javax.swing.JButton();
        sinhButton = new javax.swing.JButton();
        bracket1Button = new javax.swing.JButton();
        bracket2Button = new javax.swing.JButton();
        rclButton2 = new javax.swing.JButton();
        mrButton3 = new javax.swing.JButton();
        consButton = new javax.swing.JButton();
        drgButton = new javax.swing.JButton();
        hypButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dmsButton = new javax.swing.JButton();
        shiftButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ShiftTextdisplay = new javax.swing.JTextField();
        ansTextdisplay = new javax.swing.JTextField();
        HypTextdisplay = new javax.swing.JTextField();
        eButton = new javax.swing.JButton();
        lnButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 153));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        ApplicationWindow.setMinimumSize(new java.awt.Dimension(700, 500));
        ApplicationWindow.setOpaque(false);
        ApplicationWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        border1.setBackground(new java.awt.Color(255, 255, 255));
        border1.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout border1Layout = new javax.swing.GroupLayout(border1);
        border1.setLayout(border1Layout);
        border1Layout.setHorizontalGroup(
            border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        border1Layout.setVerticalGroup(
            border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ApplicationWindow.add(border1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        border2.setBackground(new java.awt.Color(255, 255, 255));
        border2.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout border2Layout = new javax.swing.GroupLayout(border2);
        border2.setLayout(border2Layout);
        border2Layout.setHorizontalGroup(
            border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        border2Layout.setVerticalGroup(
            border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ApplicationWindow.add(border2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 498, 700, -1));

        DisplayPanel.setOpaque(false);
        DisplayPanel.setLayout(null);

        TypeDisplay.setEditable(false);
        TypeDisplay.setBackground(new java.awt.Color(204, 204, 204));
        TypeDisplay.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        TypeDisplay.setBorder(null);
        DisplayPanel.add(TypeDisplay);
        TypeDisplay.setBounds(0, -10, 440, 50);

        AnswerDisplay1.setEditable(false);
        AnswerDisplay1.setBackground(new java.awt.Color(204, 204, 204));
        AnswerDisplay1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        AnswerDisplay1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        AnswerDisplay1.setBorder(null);
        DisplayPanel.add(AnswerDisplay1);
        AnswerDisplay1.setBounds(0, 40, 440, 40);

        Back.setEditable(false);
        Back.setBackground(new java.awt.Color(204, 204, 204));
        Back.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Back.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Back.setBorder(null);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        DisplayPanel.add(Back);
        Back.setBounds(0, 20, 440, 40);

        ApplicationWindow.add(DisplayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 44, 440, 85));

        NumberPanel.setOpaque(false);

        sevenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/seven.png"))); // NOI18N
        sevenButton.setAlignmentX(0.5F);
        sevenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sevenButton.setIconTextGap(-10);
        sevenButton.setPreferredSize(new java.awt.Dimension(60, 40));
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });

        eightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/eight.png"))); // NOI18N
        eightButton.setAlignmentX(0.5F);
        eightButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eightButton.setIconTextGap(-10);
        eightButton.setPreferredSize(new java.awt.Dimension(60, 40));
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });

        nineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/nine.png"))); // NOI18N
        nineButton.setAlignmentX(0.5F);
        nineButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nineButton.setIconTextGap(-10);
        nineButton.setPreferredSize(new java.awt.Dimension(60, 40));
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });

        cButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/del.png"))); // NOI18N
        cButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cButton.setIconTextGap(-10);
        cButton.setPreferredSize(new java.awt.Dimension(60, 40));
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        acButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/ac.png"))); // NOI18N
        acButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acButton.setIconTextGap(-10);
        acButton.setPreferredSize(new java.awt.Dimension(60, 40));
        acButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acButtonActionPerformed(evt);
            }
        });

        minusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/minus.png"))); // NOI18N
        minusButton.setAlignmentX(0.5F);
        minusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minusButton.setIconTextGap(-10);
        minusButton.setPreferredSize(new java.awt.Dimension(60, 40));
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        divisionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/division.png"))); // NOI18N
        divisionButton.setAlignmentX(0.5F);
        divisionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        divisionButton.setIconTextGap(-10);
        divisionButton.setPreferredSize(new java.awt.Dimension(60, 40));
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonActionPerformed(evt);
            }
        });

        equalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/equal.png"))); // NOI18N
        equalButton.setAlignmentX(0.5F);
        equalButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equalButton.setIconTextGap(-10);
        equalButton.setPreferredSize(new java.awt.Dimension(60, 40));
        equalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalButtonActionPerformed(evt);
            }
        });

        signButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/sign.png"))); // NOI18N
        signButton.setAlignmentX(0.5F);
        signButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signButton.setIconTextGap(-10);
        signButton.setPreferredSize(new java.awt.Dimension(60, 40));
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonActionPerformed(evt);
            }
        });

        multiplyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/multiply.png"))); // NOI18N
        multiplyButton.setAlignmentX(0.5F);
        multiplyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multiplyButton.setIconTextGap(-10);
        multiplyButton.setPreferredSize(new java.awt.Dimension(60, 40));
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        plusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/plus.png"))); // NOI18N
        plusButton.setAlignmentX(0.5F);
        plusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plusButton.setIconTextGap(-10);
        plusButton.setPreferredSize(new java.awt.Dimension(60, 40));
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        threeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/three.png"))); // NOI18N
        threeButton.setAlignmentX(0.5F);
        threeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        threeButton.setIconTextGap(-10);
        threeButton.setPreferredSize(new java.awt.Dimension(60, 40));
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        sixButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/six.png"))); // NOI18N
        sixButton.setAlignmentX(0.5F);
        sixButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sixButton.setIconTextGap(-10);
        sixButton.setPreferredSize(new java.awt.Dimension(60, 40));
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        expButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/exp.png"))); // NOI18N
        expButton.setAlignmentX(0.5F);
        expButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expButton.setIconTextGap(-10);
        expButton.setPreferredSize(new java.awt.Dimension(60, 40));
        expButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expButtonActionPerformed(evt);
            }
        });

        dotButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/dot.png"))); // NOI18N
        dotButton.setAlignmentX(0.5F);
        dotButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dotButton.setIconTextGap(-10);
        dotButton.setPreferredSize(new java.awt.Dimension(60, 40));
        dotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonActionPerformed(evt);
            }
        });

        twoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/two.png"))); // NOI18N
        twoButton.setAlignmentX(0.5F);
        twoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twoButton.setIconTextGap(-10);
        twoButton.setPreferredSize(new java.awt.Dimension(60, 40));
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        fiveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/five.png"))); // NOI18N
        fiveButton.setAlignmentX(0.5F);
        fiveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fiveButton.setIconTextGap(-10);
        fiveButton.setPreferredSize(new java.awt.Dimension(60, 40));
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        fourButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/four.png"))); // NOI18N
        fourButton.setToolTipText("");
        fourButton.setAlignmentX(0.5F);
        fourButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fourButton.setIconTextGap(-10);
        fourButton.setPreferredSize(new java.awt.Dimension(60, 40));
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        oneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/one.png"))); // NOI18N
        oneButton.setAlignmentX(0.5F);
        oneButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oneButton.setIconTextGap(-10);
        oneButton.setPreferredSize(new java.awt.Dimension(60, 40));
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        zeroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/0.png"))); // NOI18N
        zeroButton.setAlignmentX(0.5F);
        zeroButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        zeroButton.setIconTextGap(-10);
        zeroButton.setPreferredSize(new java.awt.Dimension(60, 40));
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NumberPanelLayout = new javax.swing.GroupLayout(NumberPanel);
        NumberPanel.setLayout(NumberPanelLayout);
        NumberPanelLayout.setHorizontalGroup(
            NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NumberPanelLayout.createSequentialGroup()
                        .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(acButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NumberPanelLayout.createSequentialGroup()
                        .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NumberPanelLayout.createSequentialGroup()
                        .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NumberPanelLayout.createSequentialGroup()
                        .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(dotButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(expButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(signButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NumberPanelLayout.setVerticalGroup(
            NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dotButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ApplicationWindow.add(NumberPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 460, 200));

        ShiftKeyPanel.setOpaque(false);
        ShiftKeyPanel.setLayout(new java.awt.CardLayout());

        DefPanel1.setOpaque(false);
        DefPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sqrButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/xsqr.png"))); // NOI18N
        sqrButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sqrButton.setIconTextGap(-10);
        sqrButton.setPreferredSize(new java.awt.Dimension(50, 35));
        sqrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrButtonActionPerformed(evt);
            }
        });
        DefPanel1.add(sqrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        sqrtButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/xsqrt.png"))); // NOI18N
        sqrtButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sqrtButton.setIconTextGap(-10);
        sqrtButton.setPreferredSize(new java.awt.Dimension(50, 35));
        sqrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtButtonActionPerformed(evt);
            }
        });
        DefPanel1.add(sqrtButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 30));

        logButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/log.png"))); // NOI18N
        logButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logButton.setIconTextGap(-10);
        logButton.setPreferredSize(new java.awt.Dimension(50, 35));
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });
        DefPanel1.add(logButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 30));

        xinvButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/xinv.png"))); // NOI18N
        xinvButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xinvButton.setIconTextGap(-10);
        xinvButton.setPreferredSize(new java.awt.Dimension(50, 35));
        xinvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xinvButtonActionPerformed(evt);
            }
        });
        DefPanel1.add(xinvButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/labelxfact.png"))); // NOI18N
        DefPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/labelxpwr.png"))); // NOI18N
        jLabel6.setToolTipText("");
        DefPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/labelantilog.png"))); // NOI18N
        DefPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/labelcubrt.png"))); // NOI18N
        DefPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 20));

        ShiftKeyPanel.add(DefPanel1, "card3");

        PressedShift1.setBackground(new java.awt.Color(51, 51, 255));
        PressedShift1.setOpaque(false);
        PressedShift1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xpwrButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/xpwr.png"))); // NOI18N
        xpwrButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xpwrButton.setIconTextGap(-10);
        xpwrButton.setPreferredSize(new java.awt.Dimension(50, 35));
        xpwrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xpwrButtonActionPerformed(evt);
            }
        });
        PressedShift1.add(xpwrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        cubicRtButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/cubicRt.png"))); // NOI18N
        cubicRtButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cubicRtButton.setIconTextGap(-10);
        cubicRtButton.setPreferredSize(new java.awt.Dimension(50, 35));
        cubicRtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubicRtButtonActionPerformed(evt);
            }
        });
        PressedShift1.add(cubicRtButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 30));

        xFactButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/xFact.png"))); // NOI18N
        xFactButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xFactButton.setIconTextGap(-10);
        xFactButton.setPreferredSize(new java.awt.Dimension(50, 35));
        xFactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xFactButtonActionPerformed(evt);
            }
        });
        PressedShift1.add(xFactButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 30));

        AntilogButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/antilog.png"))); // NOI18N
        AntilogButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AntilogButton.setIconTextGap(-10);
        AntilogButton.setPreferredSize(new java.awt.Dimension(50, 35));
        AntilogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntilogButtonActionPerformed(evt);
            }
        });
        PressedShift1.add(AntilogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 30));

        ShiftKeyPanel.add(PressedShift1, "card2");

        ApplicationWindow.add(ShiftKeyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 124, 150, 120));

        TrigonomerticPanel.setOpaque(false);
        TrigonomerticPanel.setLayout(new java.awt.CardLayout());

        DefPanel2.setOpaque(false);
        DefPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sinButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/sin.png"))); // NOI18N
        sinButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sinButton.setIconTextGap(-10);
        sinButton.setPreferredSize(new java.awt.Dimension(50, 35));
        sinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinButtonActionPerformed(evt);
            }
        });
        DefPanel2.add(sinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 30));

        cosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/cos.png"))); // NOI18N
        cosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cosButton.setIconTextGap(-10);
        cosButton.setPreferredSize(new java.awt.Dimension(50, 35));
        cosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosButtonActionPerformed(evt);
            }
        });
        DefPanel2.add(cosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 30));

        tanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/tan.png"))); // NOI18N
        tanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tanButton.setIconTextGap(-10);
        tanButton.setPreferredSize(new java.awt.Dimension(50, 35));
        tanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanButtonActionPerformed(evt);
            }
        });
        DefPanel2.add(tanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 32));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/labeltaninv.png"))); // NOI18N
        DefPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/labelsininv.png"))); // NOI18N
        DefPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/labelcosinv.png"))); // NOI18N
        jLabel10.setText("jLabel7");
        DefPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 20));

        TrigonomerticPanel.add(DefPanel2, "card2");

        PressedShift2.setOpaque(false);
        PressedShift2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invSinButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/invSin.png"))); // NOI18N
        invSinButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invSinButton.setIconTextGap(-10);
        invSinButton.setPreferredSize(new java.awt.Dimension(50, 35));
        invSinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invSinButtonActionPerformed(evt);
            }
        });
        PressedShift2.add(invSinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, -1, 30));

        invCosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/invCos.png"))); // NOI18N
        invCosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invCosButton.setIconTextGap(-10);
        invCosButton.setPreferredSize(new java.awt.Dimension(50, 35));
        invCosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invCosButtonActionPerformed(evt);
            }
        });
        PressedShift2.add(invCosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 30));

        invTanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/invTan.png"))); // NOI18N
        invTanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invTanButton.setIconTextGap(-10);
        invTanButton.setPreferredSize(new java.awt.Dimension(50, 35));
        invTanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invTanButtonActionPerformed(evt);
            }
        });
        PressedShift2.add(invTanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, -1, 32));

        TrigonomerticPanel.add(PressedShift2, "card4");

        PressedHyp.setOpaque(false);
        PressedHyp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tanhButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/tanh.png"))); // NOI18N
        tanhButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tanhButton.setIconTextGap(-10);
        tanhButton.setPreferredSize(new java.awt.Dimension(50, 35));
        tanhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanhButtonActionPerformed(evt);
            }
        });
        PressedHyp.add(tanhButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, -1, 32));

        coshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/cosh.png"))); // NOI18N
        coshButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coshButton.setIconTextGap(-10);
        coshButton.setPreferredSize(new java.awt.Dimension(50, 35));
        coshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coshButtonActionPerformed(evt);
            }
        });
        PressedHyp.add(coshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 30));

        sinhButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/sinh.png"))); // NOI18N
        sinhButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sinhButton.setIconTextGap(-10);
        sinhButton.setPreferredSize(new java.awt.Dimension(50, 35));
        sinhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinhButtonActionPerformed(evt);
            }
        });
        PressedHyp.add(sinhButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, -1, 30));

        TrigonomerticPanel.add(PressedHyp, "card3");

        ApplicationWindow.add(TrigonomerticPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 50, 160));

        bracket1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/bracket1.png"))); // NOI18N
        bracket1Button.setAlignmentX(0.5F);
        bracket1Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bracket1Button.setIconTextGap(-10);
        bracket1Button.setPreferredSize(new java.awt.Dimension(60, 40));
        bracket1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bracket1ButtonActionPerformed(evt);
            }
        });
        ApplicationWindow.add(bracket1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 50, 30));

        bracket2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/bracket2.png"))); // NOI18N
        bracket2Button.setAlignmentX(0.5F);
        bracket2Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bracket2Button.setIconTextGap(-10);
        bracket2Button.setPreferredSize(new java.awt.Dimension(60, 40));
        bracket2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bracket2ButtonActionPerformed(evt);
            }
        });
        ApplicationWindow.add(bracket2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 50, 30));

        rclButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/rcl.png"))); // NOI18N
        rclButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rclButton2.setIconTextGap(-10);
        rclButton2.setPreferredSize(new java.awt.Dimension(50, 35));
        rclButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rclButton2ActionPerformed(evt);
            }
        });
        ApplicationWindow.add(rclButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, 30));

        mrButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/mr.png"))); // NOI18N
        mrButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mrButton3.setIconTextGap(-10);
        mrButton3.setPreferredSize(new java.awt.Dimension(50, 35));
        mrButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrButton3ActionPerformed(evt);
            }
        });
        ApplicationWindow.add(mrButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, 30));

        consButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/cns.png"))); // NOI18N
        consButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consButton.setIconTextGap(-10);
        consButton.setPreferredSize(new java.awt.Dimension(50, 35));
        consButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consButtonActionPerformed(evt);
            }
        });
        ApplicationWindow.add(consButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, 30));

        drgButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/drg.png"))); // NOI18N
        drgButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        drgButton.setIconTextGap(-10);
        drgButton.setPreferredSize(new java.awt.Dimension(50, 35));
        drgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drgButtonActionPerformed(evt);
            }
        });
        ApplicationWindow.add(drgButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, 30));

        hypButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/hyp.png"))); // NOI18N
        hypButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hypButton.setIconTextGap(-10);
        hypButton.setPreferredSize(new java.awt.Dimension(50, 35));
        hypButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypButtonActionPerformed(evt);
            }
        });
        ApplicationWindow.add(hypButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, 30));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Scientific Calculator");
        jLabel1.setToolTipText("");
        ApplicationWindow.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 30));

        dmsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/dms.png"))); // NOI18N
        dmsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dmsButton.setIconTextGap(-10);
        dmsButton.setPreferredSize(new java.awt.Dimension(50, 35));
        dmsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dmsButtonActionPerformed(evt);
            }
        });
        ApplicationWindow.add(dmsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, 30));

        shiftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/shift.png"))); // NOI18N
        shiftButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shiftButton.setIconTextGap(-10);
        shiftButton.setPreferredSize(new java.awt.Dimension(50, 35));
        shiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftButtonActionPerformed(evt);
            }
        });
        ApplicationWindow.add(shiftButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 28));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/pan.png"))); // NOI18N
        ApplicationWindow.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 100, -1));

        ShiftTextdisplay.setEditable(false);
        ShiftTextdisplay.setBackground(new java.awt.Color(51, 51, 51));
        ShiftTextdisplay.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        ShiftTextdisplay.setForeground(new java.awt.Color(255, 255, 0));
        ShiftTextdisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ShiftTextdisplay.setBorder(null);
        ApplicationWindow.add(ShiftTextdisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 50, 30));

        ansTextdisplay.setEditable(false);
        ansTextdisplay.setBackground(new java.awt.Color(51, 51, 51));
        ansTextdisplay.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        ansTextdisplay.setForeground(new java.awt.Color(255, 255, 0));
        ansTextdisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ansTextdisplay.setBorder(null);
        ApplicationWindow.add(ansTextdisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 40, 30));

        HypTextdisplay.setEditable(false);
        HypTextdisplay.setBackground(new java.awt.Color(51, 51, 51));
        HypTextdisplay.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        HypTextdisplay.setForeground(new java.awt.Color(204, 255, 153));
        HypTextdisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HypTextdisplay.setBorder(null);
        ApplicationWindow.add(HypTextdisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 40, 30));

        eButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/e.png"))); // NOI18N
        eButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eButton.setIconTextGap(-10);
        eButton.setPreferredSize(new java.awt.Dimension(50, 35));
        eButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eButtonActionPerformed(evt);
            }
        });
        ApplicationWindow.add(eButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, 30));

        lnButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CalculatorButtons/ln.png"))); // NOI18N
        lnButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lnButton1.setIconTextGap(-10);
        lnButton1.setPreferredSize(new java.awt.Dimension(50, 35));
        lnButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnButton1ActionPerformed(evt);
            }
        });
        ApplicationWindow.add(lnButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, 30));

        add(ApplicationWindow, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void hypButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypButtonActionPerformed
        if(!ShiftTextdisplay.getText().equals("SHIFT") && !HypTextdisplay.getText().equals("Hyp")){
            //this will show the Hyp text
            HypTextdisplay.setText("Hyp");
            
            
            //this will make visible the Hyperbolic action keys
            TrigonomerticPanel.removeAll();
            TrigonomerticPanel.setSize(PressedHyp.getSize());
            TrigonomerticPanel.add(PressedHyp);
            TrigonomerticPanel.repaint();
            TrigonomerticPanel.revalidate();
            
        }
        //If shift is pressed once, it will show remove Hyperbolic action
        else{
            ShiftTextdisplay.setText("");
            HypTextdisplay.setText("");
            
            //this will remove all buttons that appeared after pressing the Hyperbolic key
            TrigonomerticPanel.removeAll();
            TrigonomerticPanel.setSize(DefPanel2.getSize());
            TrigonomerticPanel.add(DefPanel2);
            TrigonomerticPanel.repaint();
            TrigonomerticPanel.revalidate();
            
            ShiftKeyPanel.removeAll();
            ShiftKeyPanel.setSize(DefPanel1.getSize());
            ShiftKeyPanel.add(DefPanel1);
            ShiftKeyPanel.repaint();
            ShiftKeyPanel.revalidate();
        }
    }//GEN-LAST:event_hypButtonActionPerformed

    private void drgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drgButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drgButtonActionPerformed

    private void consButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consButtonActionPerformed

    private void sinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sinButtonActionPerformed

    private void cosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cosButtonActionPerformed

    private void lnButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnButton1ActionPerformed

    private void tanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logButtonActionPerformed

    private void sqrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sqrButtonActionPerformed

    private void mrButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrButton3ActionPerformed

    private void rclButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rclButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rclButton2ActionPerformed

    private void xinvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xinvButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xinvButtonActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"2");
    }//GEN-LAST:event_twoButtonActionPerformed

    private void dmsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dmsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dmsButtonActionPerformed

    private void xpwrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xpwrButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xpwrButtonActionPerformed

    private void sqrtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sqrtButtonActionPerformed

    private void eButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eButtonActionPerformed

    private void signButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signButtonActionPerformed

    private void shiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftButtonActionPerformed
        //If shift is not pressed before, it will show SHIFT message above the display and do shift actions
        if(!ShiftTextdisplay.getText().equals("SHIFT") && !HypTextdisplay.getText().equals("Hyp")){
            //this will show the SHIFT text
            ShiftTextdisplay.setText("SHIFT");
            
            
            //this will make visible the shift action keys
            ShiftKeyPanel.removeAll();
            ShiftKeyPanel.setSize(PressedShift1.getSize());
            ShiftKeyPanel.add(PressedShift1);
            ShiftKeyPanel.repaint();
            ShiftKeyPanel.revalidate();
            
            TrigonomerticPanel.removeAll();
            TrigonomerticPanel.setSize(PressedShift2.getSize());
            TrigonomerticPanel.add(PressedShift2);
            TrigonomerticPanel.repaint();
            TrigonomerticPanel.revalidate();
            
        }
        //If shift is pressed once, it will show remove SHIFT action
        else{
            ShiftTextdisplay.setText("");
            HypTextdisplay.setText("");
            
            //this will remove all buttons that appeared after pressing the shift key
            ShiftKeyPanel.removeAll();
            ShiftKeyPanel.setSize(DefPanel1.getSize());
            ShiftKeyPanel.add(DefPanel1);
            ShiftKeyPanel.repaint();
            ShiftKeyPanel.revalidate();
            
            TrigonomerticPanel.removeAll();
            TrigonomerticPanel.setSize(DefPanel2.getSize());
            TrigonomerticPanel.add(DefPanel2);
            TrigonomerticPanel.repaint();
            TrigonomerticPanel.revalidate();
        }
    }//GEN-LAST:event_shiftButtonActionPerformed
    
    private void sinhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinhButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sinhButtonActionPerformed

    private void coshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coshButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coshButtonActionPerformed

    private void tanhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanhButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanhButtonActionPerformed

    private void invSinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invSinButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invSinButtonActionPerformed

    private void invCosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invCosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invCosButtonActionPerformed

    private void invTanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invTanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invTanButtonActionPerformed

    private void cubicRtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubicRtButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cubicRtButtonActionPerformed

    private void xFactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xFactButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xFactButtonActionPerformed

    private void AntilogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntilogButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AntilogButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"0");
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void dotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dotButtonActionPerformed

    private void expButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expButtonActionPerformed

    private void divisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"/");
    }//GEN-LAST:event_divisionButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"*");
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"6");
    }//GEN-LAST:event_sixButtonActionPerformed

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"1");
    }//GEN-LAST:event_oneButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"4");
    }//GEN-LAST:event_fourButtonActionPerformed

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"5");
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"3");
    }//GEN-LAST:event_threeButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"+");
    }//GEN-LAST:event_plusButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"-");
    }//GEN-LAST:event_minusButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"9");
    }//GEN-LAST:event_nineButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"8");
    }//GEN-LAST:event_eightButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"7");
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void bracket1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bracket1ButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+"(");
    }//GEN-LAST:event_bracket1ButtonActionPerformed

    private void bracket2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bracket2ButtonActionPerformed
        TypeDisplay.setText(TypeDisplay.getText()+")");
    }//GEN-LAST:event_bracket2ButtonActionPerformed

    private void equalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equalButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cButtonActionPerformed

    private void acButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnswerDisplay1;
    private javax.swing.JButton AntilogButton;
    private javax.swing.JPanel ApplicationWindow;
    private javax.swing.JTextField Back;
    private javax.swing.JPanel DefPanel1;
    private javax.swing.JPanel DefPanel2;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JTextField HypTextdisplay;
    private javax.swing.JPanel NumberPanel;
    private javax.swing.JPanel PressedHyp;
    private javax.swing.JPanel PressedShift1;
    private javax.swing.JPanel PressedShift2;
    private javax.swing.JPanel ShiftKeyPanel;
    private javax.swing.JTextField ShiftTextdisplay;
    private javax.swing.JPanel TrigonomerticPanel;
    private javax.swing.JTextField TypeDisplay;
    private javax.swing.JButton acButton;
    private javax.swing.JTextField ansTextdisplay;
    private javax.swing.JPanel border1;
    private javax.swing.JPanel border2;
    private javax.swing.JButton bracket1Button;
    private javax.swing.JButton bracket2Button;
    private javax.swing.JButton cButton;
    private javax.swing.JButton consButton;
    private javax.swing.JButton cosButton;
    private javax.swing.JButton coshButton;
    private javax.swing.JButton cubicRtButton;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton dmsButton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton drgButton;
    private javax.swing.JButton eButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JButton expButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton hypButton;
    private javax.swing.JButton invCosButton;
    private javax.swing.JButton invSinButton;
    private javax.swing.JButton invTanButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton lnButton1;
    private javax.swing.JButton logButton;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton mrButton3;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton rclButton2;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton shiftButton;
    private javax.swing.JButton signButton;
    private javax.swing.JButton sinButton;
    private javax.swing.JButton sinhButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton sqrButton;
    private javax.swing.JButton sqrtButton;
    private javax.swing.JButton tanButton;
    private javax.swing.JButton tanhButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton xFactButton;
    private javax.swing.JButton xinvButton;
    private javax.swing.JButton xpwrButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
